service: lists
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-west-2

  environment:
    LISTS_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    LIST_ITEMS_TABLE: list-items-${opt:stage, self:provider.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"
functions:
  listsGetAll:
    handler: api/v1/lists.getAll
    memorySize: 128
    description: Get all lists.
    events:
      - http: 
          path: v1/lists 
          method: get
  listsCreateOne:
    handler: api/v1/lists.createOne
    memorySize: 128
    description: Create a list.
    events:
      - http:
          path: v1/lists
          method: post
  listsDeleteOne:
    handler: api/v1/lists.deleteOne
    memorySize: 128
    description: Delete a list.
    events:
      - http:
          path: v1/lists/{id}
          method: delete
  listsGetOne:
    handler: api/v1/lists.getOne
    memorySize: 128
    description: Get list details by id.
    events:
      - http:
          path: v1/lists/{id}
          method: get
resources:
  Resources:
    ListsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "id"
            AttributeType: "S"   
        KeySchema:
          -
            AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.LISTS_TABLE}
    ListItemsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "id"
            AttributeType: "S"   
        KeySchema:
          -
            AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.LIST_ITEMS_TABLE}

